### ISSUE TITLE
 No module named 'pyngrok'

### ISSUE THREAD

**Issue by presmedia002** [kurogai/nero-phishing-server#1]
/nero-phishing-server# python3 nero.py
Traceback (most recent call last):
  File "nero.py", line 4, in <module>
    import httpd
  File "/root/nero-phishing-server/httpd.py", line 5, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by unknownspider** [comment]
@presmedia002 
I'm having the same error were you able to fix it?

Thanks!

**Comment by unknownspider** [comment]
@presmedia002 

If you are in Kali make sure you installed pip3 then from terminal make sure you install pyngrok:

`sudo pip3 install pyngrok`

Try again to run `python3 nero.py `

**Comment by kurogai** [comment]
sudo pip3 install pyngrok

Try it, and response back here 👍

**Comment by davie709** [comment]
try :
sudo pip install pyngrok
