### ISSUE TITLE
where is the link getting created here?

### ISSUE THREAD

**Issue by presmedia002** [kurogai/nero-phishing-server#2]
nero > set url https://somedomain.com/login https
[+] URL sent: https://somedomain.com/login
nero > 

where is the link getting created here?

**Comment by kurogai** [comment]
That's just an debug message. The final url should come after the "run" command

**Comment by presmedia002** [comment]
https://e32895ecd20c.ngrok.io/
i have made this link but its says gateway time out

**Comment by kurogai** [comment]
Please past here the images from terminal, and from the browser, will help a lot.

**Comment by presmedia002** [comment]
https://e32895ecd20c.ngrok.io/
i have made this link but its says gateway time out


/'

**Comment by kurogai** [comment]
You're only able to generate one link peer session with an expiration of 7h (by default from Ngrok).

If yoh generate an url like:

https://oaow8hdwkwpp.ngrok/

You have 7h to use it. But, if you turn off the program, the link will be lost, and you will need to generate another.
